#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""读取 assets/gallery/provenance.json，生成 gallery-data.js（供 HTML 弹窗读取，相对路径）。"""
import json, os, collections

BASE = "/Users/bytedance/workspace/travel-books/trips/2026-10-哈萨克斯坦-阿拉木图阿克套"
PROV = os.path.join(BASE, "assets/gallery/provenance.json")
OUTJS = os.path.join(BASE, "assets/gallery/gallery-data.js")

TITLE = {
 "citywalk_cathedral":"升天大教堂 · 潘菲洛夫公园",
 "citywalk_memorial":"28 勇士公园 · 永恒之火",
 "citywalk_mosque":"中央清真寺",
 "citywalk_metro":"阿拉木图苏式地铁站",
 "citywalk_brutalism":"粗野主义 · 苏式建筑专线",
 "citywalk_street":"Citywalk 街巷与小店",
 "green_bazaar":"绿巴扎 Green Bazaar",
 "barakholka_flea":"Barakholka 旧货大巴扎",
 "koktobe":"Kok Tobe 科克托别山",
 "museum":"博物馆",
 "bao_pipe":"管道徒步上大阿拉木图湖 BAO",
 "glacier":"博格达诺维奇冰川 · 冰洞",
 "charyn":"恰伦峡谷 Charyn",
 "kolsai_kaindy":"科尔赛湖 / 卡因迪湖",
 "aktau_city":"阿克套市区与里海岸",
 "mangystau_seabed":"曼吉斯套 · 远古海床遗迹",
 "alt_kyzylkup":"Kyzylkup 提拉米苏峡谷",
 "alt_bozzhyra":"Bozzhyra / Tuzbair 南线",
 "alt_shakpak_ata":"Shakpak-Ata 地下清真寺",
 "food_smile":"Smile / Shashlychok 红房子烤肉",
 "food_navat":"Navat 国菜食堂",
 "food_hosejosper":"Hose & Josper 牛排",
 "food_auyl":"Auyl 游牧创意菜",
 "food_local":"其他本地餐厅实拍",
}

def main():
    prov = json.load(open(PROV, encoding="utf-8"))
    data = collections.OrderedDict()
    for key, items in prov.items():
        data[key] = {
            "title": TITLE.get(key, key),
            "items": [{
                "src": f"assets/gallery/{key}/{it['file']}",
                "cap": it["title"],
                "url": it["url"],
                "like": it.get("like") or "",
            } for it in items]
        }
    with open(OUTJS, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by tools/build_gallery_js.py · 图片均来自小红书公开笔记，版权归原作者，仅作个人行程参考 */\n")
        f.write("window.GALLERY=")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print("keys:", len(data), "total imgs:", sum(len(v['items']) for v in data.values()))
    print("size KB:", round(os.path.getsize(OUTJS)/1024,1))

if __name__ == "__main__":
    main()
